hamiltonian: ising-1d
compute_maximum_time: false
compute_reference: true
use_full_rank_matrix: false
n_sites: 6
J: 1.
g: 0.75
h: 0.6
disordered: false
degree: 4
n_repetitions: 10
t: 2.
max_bond_dim: 128
compress: true
degree_thres: 4
n_rep_thres: 8
fac_thres: 10
reference_number_start: 1
reference_seed: 
- 0